In [1]:
import pandas as pd
import numpy as np

In [2]:
from tensorflow.keras import datasets

In [3]:
(x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()

In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [6]:
x_test

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
x_train.shape

(60000, 28, 28)

In [10]:
y_train.shape

(60000,)

In [11]:
x_test.shape

(10000, 28, 28)

In [12]:
y_test.shape

(10000,)

In [13]:
width,height = 28,28
input_shape = (height,width,1)

In [14]:
input_shape

(28, 28, 1)

In [15]:
x_train = x_train.reshape(x_train.shape[0],height,width,1)

x_test = x_test.reshape(x_test.shape[0],height,width,1)

In [16]:
x_train.shape

(60000, 28, 28, 1)

In [17]:
y_train.shape

(60000,)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(x_train,y_train,test_size=0.1)

In [19]:
len(x_val)

6000

In [20]:
x_train = (x_train - x_train.mean() / x_train.std())
x_val = (x_val - x_val.mean() / x_val.std())
x_test = (x_test - x_test.mean() / x_test.std())

In [21]:
y_train

array([5, 6, 3, ..., 1, 1, 6], dtype=uint8)

In [22]:
from tensorflow import keras

In [23]:
num_labels = 10
y_train = keras.utils.to_categorical(y_train)

In [24]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

In [25]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
y_val

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

# Model

In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten,Input,Conv2D, MaxPooling2D,AveragePooling2D

In [29]:
model = Sequential()
model.add(Conv2D(6, kernel_size = (5,5),strides = (1,1),activation = "tanh" , input_shape = (28,28,1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5,5),strides = (1,1), activation = "tanh"))
model.add(AveragePooling2D(pool_size = (2,2), strides = (2,2)))
model.add(Conv2D(120,kernel_size = (5,5),strides = (1,1), activation = "tanh"))

model.add(Flatten())
model.add(Dense(84 , activation = "tanh"))
model.add(Dense(num_labels , activation = "softmax"))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [30]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 23, 23, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 19, 19, 16)        2416      
_________________________________________________________________
average_pooling2d_1 (Average (None, 9, 9, 16)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 5, 5, 120)         48120     
_________________________________________________________________
flatten (Flatten)            (None, 3000)              0         
_________________________________________________________________
dense (Dense)                (None, 84)                2

In [31]:
model.compile(loss = keras.losses.categorical_crossentropy , optimizer = "adam" ,metrics = ["accuracy"])

In [32]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data=(x_val,y_val))

Train on 54000 samples, validate on 6000 samples
Epoch 1/20
54000/54000 [==============================] - 33s 604us/sample - loss: 0.1629 - acc: 0.9511 - val_loss: 0.1266 - val_acc: 0.9627
Epoch 2/20
54000/54000 [==============================] - 36s 666us/sample - loss: 0.0942 - acc: 0.9723 - val_loss: 0.0836 - val_acc: 0.9728
Epoch 3/20
54000/54000 [==============================] - 37s 684us/sample - loss: 0.0829 - acc: 0.9745 - val_loss: 0.0891 - val_acc: 0.9715
Epoch 4/20
54000/54000 [==============================] - 38s 695us/sample - loss: 0.0751 - acc: 0.9774 - val_loss: 0.0902 - val_acc: 0.9705
Epoch 5/20
54000/54000 [==============================] - 36s 671us/sample - loss: 0.0741 - acc: 0.9768 - val_loss: 0.0830 - val_acc: 0.9755
Epoch 6/20
54000/54000 [==============================] - 37s 680us/sample - loss: 0.0635 - acc: 0.9809 - val_loss: 0.0749 - val_acc: 0.9768
Epoch 7/20
54000/54000 [==============================] - 35s 648us/sample - loss: 0.0641 - acc: 0.9805 -

In [33]:
score = model.evaluate(x_test,y_test, verbose = 1)

10000/10000 [==============================] - 3s 278us/sample - loss: 0.0552 - acc: 0.9833


In [34]:
score

[0.05523882815833203, 0.9833]